import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { InspectionSession, Severity } from "@/types/inspection";

const SEVERITY_LABELS: Record<Severity, string> = {
  critical: "CRITICAL",
  major: "MAJOR",
  minor: "MINOR",
  info: "INFO",
};

const SEVERITY_COLORS: Record<Severity, [number, number, number]> = {
  critical: [220, 38, 38],
  major: [234, 88, 12],
  minor: [202, 138, 4],
  info: [37, 99, 235],
};

export function generateReport(session: InspectionSession): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Electrical Panel Inspection Report", pageWidth / 2, y, {
    align: "center",
  });
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Generated by Ironhand Inspection Assistant", pageWidth / 2, y, {
    align: "center",
  });
  y += 15;

  // Divider
  doc.setDrawColor(200);
  doc.line(14, y, pageWidth - 14, y);
  y += 10;

  // Session Info
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Inspection Details", 14, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const details = [
    ["Address:", session.address || "Not specified"],
    ["Inspector:", session.inspectorName || "Not specified"],
    ["Panel Type:", session.panelType || "Not specified"],
    ["Service:", session.serviceAmps || "Not specified"],
    ["Date:", new Date(session.startedAt).toLocaleDateString()],
    ["Duration:", formatDuration(session.startedAt, session.completedAt)],
  ];

  for (const [label, value] of details) {
    doc.setFont("helvetica", "bold");
    doc.text(label, 14, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, 55, y);
    y += 6;
  }
  y += 8;

  // Summary
  const criticalCount = session.issues.filter((i) => i.severity === "critical").length;
  const majorCount = session.issues.filter((i) => i.severity === "major").length;
  const minorCount = session.issues.filter((i) => i.severity === "minor").length;
  const infoCount = session.issues.filter((i) => i.severity === "info").length;
  const completedCount = session.checklist.filter((c) => c.status === "completed").length;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 14, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Checklist: ${completedCount} of ${session.checklist.length} items completed`,
    14,
    y
  );
  y += 6;
  doc.text(`Total Issues Found: ${session.issues.length}`, 14, y);
  y += 6;

  // Issue severity summary boxes
  const summaryItems = [
    { label: "Critical", count: criticalCount, color: SEVERITY_COLORS.critical },
    { label: "Major", count: majorCount, color: SEVERITY_COLORS.major },
    { label: "Minor", count: minorCount, color: SEVERITY_COLORS.minor },
    { label: "Info", count: infoCount, color: SEVERITY_COLORS.info },
  ];

  const boxWidth = 40;
  const boxSpacing = 4;
  let boxX = 14;
  y += 4;

  for (const item of summaryItems) {
    doc.setFillColor(...item.color);
    doc.roundedRect(boxX, y, boxWidth, 18, 2, 2, "F");
    doc.setTextColor(255);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(String(item.count), boxX + boxWidth / 2, y + 8, { align: "center" });
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(item.label, boxX + boxWidth / 2, y + 14, { align: "center" });
    boxX += boxWidth + boxSpacing;
  }

  doc.setTextColor(0);
  y += 28;

  // Checklist Table
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Inspection Checklist", 14, y);
  y += 4;

  const checklistRows = session.checklist.map((item) => [
    item.category,
    item.title,
    item.status === "completed"
      ? "PASS"
      : item.status === "skipped"
        ? "SKIPPED"
        : "NOT CHECKED",
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Category", "Item", "Status"]],
    body: checklistRows,
    headStyles: { fillColor: [31, 41, 55], fontSize: 9 },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 35 },
      2: { cellWidth: 30, halign: "center" },
    },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 2) {
        const val = data.cell.raw as string;
        if (val === "PASS") {
          data.cell.styles.textColor = [22, 163, 74];
          data.cell.styles.fontStyle = "bold";
        } else if (val === "NOT CHECKED") {
          data.cell.styles.textColor = [156, 163, 175];
        } else {
          data.cell.styles.textColor = [202, 138, 4];
        }
      }
    },
  });

  // Issues Detail
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable?.finalY + 12 || y + 60;

  if (session.issues.length > 0) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Issues Found", 14, y);
    y += 4;

    const issueRows = session.issues.map((issue) => [
      SEVERITY_LABELS[issue.severity],
      issue.title,
      issue.description,
      issue.necReference || "—",
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Severity", "Issue", "Description", "NEC Ref"]],
      body: issueRows,
      headStyles: { fillColor: [31, 41, 55], fontSize: 9 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 22, halign: "center" },
        1: { cellWidth: 35 },
        3: { cellWidth: 25 },
      },
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 0) {
          const val = data.cell.raw as string;
          const colorMap: Record<string, [number, number, number]> = {
            CRITICAL: SEVERITY_COLORS.critical,
            MAJOR: SEVERITY_COLORS.major,
            MINOR: SEVERITY_COLORS.minor,
            INFO: SEVERITY_COLORS.info,
          };
          if (colorMap[val]) {
            data.cell.styles.textColor = colorMap[val];
            data.cell.styles.fontStyle = "bold";
          }
        }
      },
    });
  }

  // Notes
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable?.finalY + 12 || y + 10;
  if (session.notes) {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Inspector Notes", 14, y);
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const splitNotes = doc.splitTextToSize(session.notes, pageWidth - 28);
    doc.text(splitNotes, 14, y);
  }

  // Footer on each page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}  |  Ironhand Inspection Report  |  ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  return doc;
}

function formatDuration(start: number, end: number | null): string {
  const endTime = end ?? Date.now();
  const ms = endTime - start;
  const minutes = Math.floor(ms / 60000);
  if (minutes < 1) return "Less than 1 minute";
  if (minutes === 1) return "1 minute";
  return `${minutes} minutes`;
}
